### ISSUE TITLE
一人血书跪求牛老师在B站更新组合导航课程

### ISSUE THREAD

**Issue by Gatsby23** [i2Nav-WHU/OB_GINS#1]

**Comment by thlsealight** [comment]
《惯性导航与组合导航原理》所有视频均已上传B站，请知悉。
本issue与OB_GINS项目无关，已关闭，请知悉。

**Comment by Gatsby23** [comment]
> 《惯性导航与组合导航原理》所有视频均已上传B站，请知悉。 本issue与OB_GINS项目无关，已关闭，请知悉。

https://www.bilibili.com/video/BV1nR4y1E7Yj?spm_id_from=333.999.0.0
OK，这边主要只看到惯性导航？

**Comment by thlsealight** [comment]
组合导航只是本课程的扩展内容，位于第二十讲，请知悉。

**Comment by Gatsby23** [comment]
> 组合导航只是本课程的扩展内容，位于第二十讲，请知悉。

好的， 谢谢
