### ISSUE TITLE
源码中residualJacobianPose0，residualJacobianPose1是怎么得到的？

### ISSUE THREAD

**Issue by JiangWeiHn** [i2Nav-WHU/OB_GINS#12]
我照着论文，看了源码，主要是preintegration_earth.cc这个文件。但有不清楚的地方，请问residualJacobianPose0，residualJacobianPose1函数内的雅可比矩阵是怎么得到的？还有residualJacobianMix0及residualJacobianMix1内的矩阵。实在没看明白，冒昧请教，请不吝赐教，拜谢。

**Comment by thlsealight** [comment]
这些表示残差对状态的一阶雅克比矩阵，如residualJacobianPose0表示残差对pose0的雅克比矩阵。限于论文的篇幅，此部分公式未包含在论文中，可由残差计算公式，通过误差扰动推导得到。

**Comment by JiangWeiHn** [comment]
谢谢
