### ISSUE TITLE
请问轮式里程计的数据如何加入imu数据文件中？

### ISSUE THREAD

**Issue by JiangWeiHn** [i2Nav-WHU/OB_GINS#13]
我想将里程计加入优化中，我们的imu是400Hz，里程计是10Hz.请问在组织imu文件时，imu和里程计时间不同步的数据行我是不是输出7列，时间同步的输出8列？

**Comment by JiangWeiHn** [comment]
另外，请教下在IC_GVINS里，采用ros的bag包，好像没有加入轮式里程计的程序，要加入，该怎么修改？

**Comment by thlsealight** [comment]
请自行阅读源代码修改，此问题超出我们的支持，我将直接关闭。
