### ISSUE TITLE
固定时间间隔的预积分因子

### ISSUE THREAD

**Issue by kk-12138** [i2Nav-WHU/OB_GINS#15]
想请教下在没有gnss观测的时刻，为什么还要固定时间间隔的添加预积分因子？
在两个gnss观测之间，做一个预积分与做多个预积分有什么不同，有什么依据吗
没有gnss全局约束，单靠多个imu预积分不是有累积误差吗？

**Comment by JiangWeiHn** [comment]
我理解是靠窗口内的前面的gnss信息约束当前的imu，估计当前的imu噪声进行修正，

**Comment by thlsealight** [comment]
预积分区间内，积分使用的是相同的IMU零偏，而IMU零偏是随时间变化的，积分区间越长，意味着变化的零偏造成的积分误差越大。此处固定间隔1秒是配合GNSS使用，同时也是为了解决这个问题，实践中可以根据具体情况处理。

我将直接关闭这个issue。
