### ISSUE TITLE
运行时出现warning。该怎么修改呢

### ISSUE THREAD

**Issue by RiErRE** [i2Nav-WHU/OB_GINS#16]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1206 14:23:07.306468  3990 preprocessor.cc:62] Specified options.num_threads: 4 exceeds maximum available from the threading model Ceres was compiled with: 2.  Bounding to maximum number available.

<img width="903" alt="warning" src="https://github.com/i2Nav-WHU/OB_GINS/assets/67326973/3e21bafd-a650-4274-8be6-05a897da6850">

**Comment by thlsealight** [comment]
如警告所示，你电脑的CPU核心数仅有2个，代码中默认设置为4，警告不影响代码运行。

我将直接关闭此issue。
