### ISSUE TITLE
是否有优化安装偏角及imu scale的预积分因子的更新计划

### ISSUE THREAD

**Issue by SpriteLin-ZJU** [i2Nav-WHU/OB_GINS#17]
你好，近期使用及学习OB_GINS获益匪浅，然后看到18维状态变量数组包含了IMU比例因子误差及安装偏角误差，但是没有实现。之后是否会开源这一部分的预积分因子内容？

**Comment by thlsealight** [comment]
> 你好，近期使用及学习OB_GINS获益匪浅，然后看到18维状态变量数组包含了IMU比例因子误差及安装偏角误差，但是没有实现。之后是否会开源这一部分的预积分因子内容？

目前没有开源这部分内容的计划哦。
