### ISSUE TITLE
(Installation) make problem

### ISSUE THREAD

**Issue by ilincaburdulea** [i2Nav-WHU/OB_GINS#18]
I am trying to use the library however I run into this problem when using make, can anybody offer some help? Thank you!

__________$ make -j$(nproc)
[  1%] Built target absl_civil_time
[  2%] Built target absl_spinlock_wait
[  3%] Built target absl_log_severity
[  4%] Built target absl_raw_logging_internal
[  5%] Built target absl_throw_delegate
[  8%] Built target absl_base
[  9%] Built target absl_int128
[ 11%] Built target absl_strings_internal
[ 18%] Built target absl_strings
[ 23%] Built target absl_time_zone
[ 26%] Built target absl_time
[ 30%] Built target absl_str_format_internal
[ 31%] Building CXX object CMakeFiles/ob_gins.dir/src/factors/pose_manifold.cc.o
In file included from ________/OB_GINS/src/factors/pose_manifold.cc:23:
________/OB_GINS/src/factors/pose_manifold.h:28:45: error: expected class-name before ‘{’ token
 class PoseManifold : public ceres::Manifold {
                                             ^
________/OB_GINS/src/factors/pose_manifold.h:31:9: error: ‘int PoseManifold::AmbientSize() const’ marked ‘override’, but does not override
     int AmbientSize() const override;
         ^~~~~~~~~~~
________/OB_GINS/src/factors/pose_manifold.h:32:9: error: ‘int PoseManifold::TangentSize() const’ marked ‘override’, but does not override
     int TangentSize() const override;
         ^~~~~~~~~~~
________/OB_GINS/src/factors/pose_manifold.h:34:10: error: ‘bool PoseManifold::Plus(const double*, const double*, double*) const’ marked ‘override’, but does not override
     bool Plus(const double *x, const double *delta, double *x_plus_delta) const override;
          ^~~~
________/OB_GINS/src/factors/pose_manifold.h:35:10: error: ‘bool PoseManifold::PlusJacobian(const double*, double*) const’ marked ‘override’, but does not override
     bool PlusJacobian(const double *x, double *jacobian) const override;
          ^~~~~~~~~~~~
________/OB_GINS/src/factors/pose_manifold.h:37:10: error: ‘bool PoseManifold::Minus(const double*, const double*, double*) const’ marked ‘override’, but does not override
     bool Minus(const double *y, const double *x, double *y_minus_x) const override;
          ^~~~~
________/OB_GINS/src/factors/pose_manifold.h:38:10: error: ‘bool PoseManifold::MinusJacobian(const double*, double*) const’ marked ‘override’, but does not override
     bool MinusJacobian(const double *x, double *jacobian) const override;
          ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/ob_gins.dir/build.make:63: CMakeFiles/ob_gins.dir/src/factors/pose_manifold.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:653: CMakeFiles/ob_gins.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by thlsealight** [comment]
Please use the newest ceres-solver version, i.e. 2.2.0.
