### ISSUE TITLE
FAILURE (Residual and Jacobain evaluation failed) 

### ISSUE THREAD

**Issue by muAluo-Juan** [i2Nav-WHU/OB_GINS#19]
Hi, 
I used OBGINS on my own dataset, but encountered the following problem. I don't know the reason and how to solve it. 

![image](https://github.com/i2Nav-WHU/OB_GINS/assets/78789974/8ef6cb59-1123-42df-bf91-ba322511c469)

I would appreciate if there is someone can help me.

This is my GNSS_RTK.pos:
![image](https://github.com/i2Nav-WHU/OB_GINS/assets/78789974/f6c39203-669f-412c-b62e-36e043474e97)

And this my ADIS16465.txt:
![image](https://github.com/i2Nav-WHU/OB_GINS/assets/78789974/0812e707-db21-4ec1-a750-513d25041c40)

**Comment by thlsealight** [comment]
Sorry for that. OB-GINS only supports the GNSS with the FPS of 1Hz. Maybe you can interpolate the GNSS.

**Comment by muAluo-Juan** [comment]
Thank you for your reply. I processed GNSS_RTK.pos so that there is only one GNSS data per second, but I still encountered this issue.

**Comment by muAluo-Juan** [comment]
Are there any other data requests that I should be aware of?

**Comment by thlsealight** [comment]
> Are there any other data requests that I should be aware of?

Maybe you can refer to the demo dataset.

**Comment by thlsealight** [comment]
The STD in your GNSS_RTK.pos file seems to be zero, and this may be the problem. You should not use a zero STD.
