### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by SuperQueen20010701** [i2Nav-WHU/OB_GINS#20]
请问OB_GINS使用的IMU数据采集系统是东北天（ENU）坐标系，但是OB_GINS在实现的时候使用的导航坐标系是NED北东地坐标系，在程序中 我没有看到哪里存在转换 还是IMU数据采集本身就是NED北东地坐标系？

**Comment by thlsealight** [comment]
请注意，ENU和NED都是导航系的一种表示方式，而IMU数据我们一般认为在一个局部的参考系，即IMU系。OB_GINS中的IMU系为前右下，数据格式请参考[格式说明](https://github.com/i2Nav-WHU/awesome-gins-datasets)。
