### ISSUE TITLE
请教关于文章中ekf好于图优化的问题

### ISSUE THREAD

**Issue by arenas7307979** [i2Nav-WHU/OB_GINS#6]
非常高兴学习这篇代码, 以下有三个问题想请教武大朋友们

1. 请教关于图优化在网站中理论上是非常有利的
http://www.i2nav.com/index/newListDetail_yw.do?newskind_id=f8990a24cf86440483d7821d9c2975c9&newsinfo_id=e8eee7a6c9314db5b69508f3b4539f33

exploring the Accuracy Potential of IMU Preintegration in Factor Graph Optimization 关于这篇文章中的比较
以ekf与m2相比, 似乎单纯在gnss-imu融合中, 基于优化的方式没有太多优势？

![image](https://user-images.githubusercontent.com/5019568/164240622-fceecb12-c9f6-4191-b1b1-c8b8f7766452.png)

2. 
关于2020这篇文章的差异
https://www.mdpi.com/2072-4292/12/18/3048
这篇似乎推导更以vins为基础去补偿地球自转，柯次力等, 
不过结果与exploring the Accuracy Potential of IMU Preintegration in Factor Graph Optimization稍有不同, 
请教是定义上有不同，需要做什么样的调整，如旋转顺序，imu定义方向不同等

3. 请教关于文档中的noise, 与 vins之间的 noise单位上存在等价转换关系吗 , 对于系统有影响吗？
ob_gins:
    arw: 0.24     # deg/sqrt(hr)
    vrw: 0.24     # m/s/sqrt(hr)
    gbstd: 50.0   # deg/hr
    abstd: 250.0  # mGal
    corrtime: 1.0 # hr

vins:
  #imu parameters       The more accurate parameters you provide, the better performance
  acc_n: 0.1          # accelerometer measurement noise standard deviation. 
  gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
  acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
  gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.

**Comment by thlsealight** [comment]
在非线性化误差较小的GNSS/INS组合导航应用中，如果GNSS观测质量良好的情况下，且IMU使用合理，图优化和EKF是等价的。而在GNSS复杂环境下，合理的进行GNSS粗差的控制，图优化会表现出更优的精度。更多信息已经邮件回复。
