### ISSUE TITLE
Question about dVel and dTheta sampling frequency

### ISSUE THREAD

**Issue by iceberg1369** [i2Nav-WHU/OB_GINS#9]
I have seen in many of your papers that icm20602 datasets are in 200hz. I would like to know the raw imu sampling freqency. is imu samples (eg 1000hz) are  trapzoidql integrated to achieve dvel and dtheta. Or it is a simple devided by 200 to represent dtheta and devel?

**Comment by thlsealight** [comment]
Actually, the raw imu is sampled in 1000Hz in our dataset, and it is integrated to achieve the dvel and the dtheta in 200Hz.
This issuse is not related to the OB_GINS itself, and it will be closed.

**Comment by iceberg1369** [comment]
thanks for reply. 
apologies for opening issue again. the timestamp of 200 Hz data is at first IMU sample or 5th IMU sample or middle?

**Comment by thlsealight** [comment]
The timestamp should be the 5th IMU sample for the delta measurement, or the middle for the velocity measurement.

**Comment by iceberg1369** [comment]
in the current study, the dTheta timestamp is 5th IMU sample and dVel timestamp is in the middle of integrated IMU samples?

**Comment by thlsealight** [comment]
> in the current study, the dTheta timestamp is 5th IMU sample and dVel timestamp is in the middle of integrated IMU samples?

The delta measurement denote the delta angle and the delta velocity, while the velocity measurement denote the angular velocity and the acceleration.
The timestamp of the 200Hz IMU data in our dataset is the timestamp of the 5th IMU sample of the 1000Hz raw IMU data.
Please do not reply in this closed issue again.
